GET http://localhost:3333/os/
####
POST http://localhost:3333/api/os/create HTTP/1.1
Content-Type: application/json

{
  "client": "HRS",
  "peca": "ZINCO PRETO",
  "quantidade": "15",
  "peso": "1.5kg",
  "valor": "1.50"
}

####
POST http://localhost:3333/user/forgot_password HTTP/1.1
Content-Type: application/json

{
  "email": "flavio.fgeremias@hotmail.com"
}